### ISSUE TITLE
Skill check rolls

### ISSUE THREAD

**Issue by hazelleberry** [weshardee/roll20-dnd5e#12]
Any time you roll a skill check, this message pops up:
No attribute was found for @{Flower| Persuasion }
or
No attribute was found for @{Flower| Insight }

but it then rolls the skill check after.

**Comment by hazelleberry** [comment]
![image](https://cloud.githubusercontent.com/assets/10823458/6014599/fccbdb3e-ab2c-11e4-80d6-a975f4f79725.png)

I think it has something to do with this.

**Comment by hazelleberry** [comment]
![image](https://cloud.githubusercontent.com/assets/10823458/6014709/e488a0b4-ab2e-11e4-9261-b807d334422c.png)

Also, I think this is related. No bonuses, total or passive trait mods are populating.

**Comment by weshardee** [comment]
Fixed.
