### ISSUE TITLE
Inventory drop down

### ISSUE THREAD

**Issue by hazelleberry** [weshardee/roll20-dnd5e#15]
![image](https://cloud.githubusercontent.com/assets/10823458/6014574/76e8696a-ab2c-11e4-9aa8-3fd67f832d95.png)

Not clear that  it's a drop down menu and selectable

**Comment by hazelleberry** [comment]
This is in general with all dropdown lists

**Comment by hazelleberry** [comment]
![image](https://cloud.githubusercontent.com/assets/10823458/6014646/d3aa4de8-ab2d-11e4-8f01-c09d5ecf410c.png)
Also also drop down lists not centered.

**Comment by weshardee** [comment]
Unfortunately, there's no way to center align a select box without replacing it entirely with JS. I have added select box indicators throughout, though.
